# Generated by Django 5.0 on 2023-12-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='campus_ambassador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='experience_expertise',
            field=models.TextField(blank=True, choices=[('Web Development', 'Web Development'), ('Android/iOS Development', 'Android/iOS Development'), ('Designer', 'Designer'), ('IOT', 'IOT'), ('Marketing', 'Marketing'), ('Operations', 'Operations'), ('Product Management', 'Product Management'), ('Business Development', 'Business Development'), ('Sales', 'Sales')], null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='favourite_startup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others'), ('Prefer not say', 'Prefer not say')], default='Prefer not say', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='have_startup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='industry_choice',
            field=models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('AR/VR', 'AR/VR'), ('AI', 'AI'), ('Automotive', 'Automotive'), ('Aviation', 'Aviation'), ('Biotech', 'Biotech'), ('Blockchain', 'Blockchain'), ('Clean Technology', 'Clean Technology'), ('Consulting', 'Consulting'), ('Consumer Goods', 'Consumer Goods'), ('Cryptocurrency', 'Cryptocurrency'), ('Cybersecurity', 'Cybersecurity'), ('Design/Graphics', 'Design/Graphics'), ('Digital Marketing', 'Digital Marketing'), ('e-Commerce', 'e-Commerece'), ('Education', 'Education'), ('Entertainment/Gaming', 'Entertainment/Gaming'), ('Events', 'Events'), ('Fashion', 'Fashion'), ('Fintech/Finance', 'Fintech/Finance'), ('Food/Beverage', 'Food/Beverage'), ('Hardware/IoT', 'Hardware/IoT'), ('Wellness and Fitness', 'Wellness and Fitness'), ('Helth Care', 'Helth Care'), ('Hospitality', 'Hospitality'), ('Human Resources', 'Human Resources'), ('IT/Services', 'IT/Services'), ('Law/Legal', 'Law/Legal'), ('Logistics/Supply Chain', 'Logistics/Supply Chain'), ('Manufacturing/Industrial', 'Manufacturing/Industrial'), ('Marketing/Advertising/Sales', 'Marketing/Advertising/Sales'), ('Media', 'Media'), ('Nanotechnology', 'Nanotechnology'), ('Nonprofits', 'Nonprofits'), ('Oil/Energy', 'Oil/Energy'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Real Estate/Construction', 'Real Estate/Construction'), ('Restaurants', 'Restaurants'), ('Retail', 'Retail'), ('SaaS', 'SaaS'), ('Services', 'Services'), ('Sports', 'Sports'), ('Telecommunication', 'Telecommunication'), ('Transport/Mobility', 'Transport/Mobility'), ('Technology', 'Technology'), ('Travel', 'Travel'), ('User Experience Design', 'User Experience Design'), ('Venture for Goods', 'Venture for Goods')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='inspiration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interest_choice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='intern_profile',
            field=models.CharField(blank=True, choices=[('Software development', 'Software development'), ('Product management', 'Product management'), ('Investment Research', 'Investment Research'), ('Business analyst', 'Business analyst'), ('Data Analysis', 'Data Analysis'), ('ML', 'ML'), ('Android App Development', 'Android App Development'), ('Web Development', 'Web Development'), ('Sales and Marketing', 'Sales and Marketing'), ('Business development', 'Business development'), ('Content creation', 'Content creation'), ('Social Media Marketing', 'Social Media Marketing'), ('Research & Development', 'Research & Development'), ('Finance', 'Finance'), ('Operations', 'Operations'), ('Back End development', 'Back End development'), ('Design', 'Design'), ('Supply Chain Management', 'Supply Chain Management'), ('Front End development', 'Front End development'), ('UI/UX Development', 'UI/UX Development')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin_id',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passing_year',
            field=models.CharField(blank=True, choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='startup_stage',
            field=models.CharField(blank=True, choices=[('Idea', 'Idea'), ('Concept', 'Concept'), ('Prototype', 'Prototype'), ('Proof Concept', 'Proof Concept'), ('Pilot', 'Pilot'), ('Operationsl(<1year)', 'Operationsl(<1year)'), ('Operational(>1year)', 'Operational(>1year)'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='want_internship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('1st Year ', '1st Year '), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year')], max_length=255, null=True),
        ),
    ]
