# Generated by Django 5.0 on 2023-12-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_studentprofile_name_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='referral_code',
        ),
    ]
