# Generated by Django 5.0 on 2023-12-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_studentprofile_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
