import user1 from "@/assets/images/users/user-1.jpg";
import user2 from "@/assets/images/users/user-2.jpg";
import user3 from "@/assets/images/users/user-3.jpg";
import user4 from "@/assets/images/users/user-4.jpg";
import user5 from "@/assets/images/users/user-5.jpg";
import user6 from "@/assets/images/users/user-6.jpg";

export const tableData = [
  {
    date: "15 Jan 2024",
    notice: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    date: "1 Jan 2024",
    notice: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    date: "25 Dec 2023",
    notice: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
];

import customer1 from "@/assets/images/all-img/customer_1.png";
export const advancedTable = [
  {
    id: 1,
    order: 951,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "3/26/2022",
    quantity: 13,
    amount: "$1779.53",
    status: "paid",
    action: null,
  },
  {
    id: 2,
    order: 238,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "2/6/2022",
    quantity: 13,
    amount: "$2215.78",
    status: "due",
    action: null,
  },
  {
    id: 3,
    order: 339,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "9/6/2021",
    quantity: 1,
    amount: "$3183.60",
    status: "due",
    action: null,
  },
  {
    id: 4,
    order: 365,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "11/7/2021",
    quantity: 13,
    amount: "$2587.86",
    status: "cancled",
    action: null,
  },
  {
    id: 5,
    order: 513,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "5/6/2022",
    quantity: 12,
    amount: "$3840.73",
    status: "paid",
    action: null,
  },
  {
    id: 6,
    order: 534,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "2/14/2022",
    quantity: 12,
    amount: "$4764.18",
    status: "cancled",
    action: null,
  },
  {
    id: 7,
    order: 77,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "7/30/2022",
    quantity: 6,
    amount: "$2875.05",
    status: "paid",
    action: null,
  },
  {
    id: 8,
    order: 238,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "6/30/2022",
    quantity: 9,
    amount: "$2491.02",
    status: "due",
    action: null,
  },
  {
    id: 9,
    order: 886,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "8/9/2022",
    quantity: 8,
    amount: "$3006.95",
    status: "due",
    action: null,
  },
  {
    id: 10,
    order: 3,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "8/4/2022",
    quantity: 12,
    amount: "$2160.32",
    status: "paid",
    action: null,
  },
  {
    id: 11,
    order: 198,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "4/5/2022",
    quantity: 8,
    amount: "$1272.66",
    status: "paid",
    action: null,
  },
  {
    id: 12,
    order: 829,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "8/9/2022",
    quantity: 2,
    amount: "$4327.86",
    status: "cancled",
    action: null,
  },
  {
    id: 13,
    order: 595,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "2/10/2022",
    quantity: 11,
    amount: "$3671.81",
    status: "cancled",
    action: null,
  },
  {
    id: 14,
    order: 374,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "2/10/2022",
    quantity: 2,
    amount: "$3401.82",
    status: "paid",
    action: null,
  },
  {
    id: 15,
    order: 32,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "5/20/2022",
    quantity: 4,
    amount: "$2387.49",
    status: "cancled",
    action: null,
  },
  {
    id: 16,
    order: 89,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "5/3/2022",
    quantity: 15,
    amount: "$4236.61",
    status: "due",
    action: null,
  },
  {
    id: 17,
    order: 912,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "10/31/2021",
    quantity: 11,
    amount: "$2975.66",
    status: "paid",
    action: null,
  },
  {
    id: 18,
    order: 621,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "1/13/2022",
    quantity: 5,
    amount: "$4576.13",
    status: "cancled",
    action: null,
  },
  {
    id: 19,
    order: 459,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "6/14/2022",
    quantity: 5,
    amount: "$1276.56",
    status: "cancled",
    action: null,
  },
  {
    id: 20,
    order: 108,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "10/8/2021",
    quantity: 4,
    amount: "$1078.64",
    status: "due",
    action: null,
  },
  {
    id: 21,
    order: 492,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "11/17/2021",
    quantity: 9,
    amount: "$1678.19",
    status: "paid",
    action: null,
  },
  {
    id: 22,
    order: 42,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "4/4/2022",
    quantity: 9,
    amount: "$1822.02",
    status: "cancled",
    action: null,
  },
  {
    id: 23,
    order: 841,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "3/21/2022",
    quantity: 5,
    amount: "$1578.39",
    status: "due",
    action: null,
  },
  {
    id: 24,
    order: 561,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "6/18/2022",
    quantity: 12,
    amount: "$2130.49",
    status: "cancled",
    action: null,
  },
  {
    id: 25,
    order: 720,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "8/15/2022",
    quantity: 8,
    amount: "$3721.11",
    status: "due",
    action: null,
  },
  {
    id: 26,
    order: 309,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "4/28/2022",
    quantity: 8,
    amount: "$4683.45",
    status: "paid",
    action: null,
  },
  {
    id: 27,
    order: 24,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "9/6/2021",
    quantity: 7,
    amount: "$2863.71",
    status: "paid",
    action: null,
  },
  {
    id: 28,
    order: 518,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "9/11/2021",
    quantity: 4,
    amount: "$3879.41",
    status: "cancled",
    action: null,
  },
  {
    id: 29,
    order: 98,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "1/27/2022",
    quantity: 5,
    amount: "$4660.81",
    status: "paid",
    action: null,
  },
  {
    id: 30,
    order: 940,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "9/16/2021",
    quantity: 6,
    amount: "$4800.75",
    status: "due",
    action: null,
  },
  {
    id: 31,
    order: 925,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "1/8/2022",
    quantity: 1,
    amount: "$2299.05",
    status: "cancled",
    action: null,
  },
  {
    id: 32,
    order: 122,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "11/18/2021",
    quantity: 1,
    amount: "$3578.02",
    status: "paid",
    action: null,
  },
  {
    id: 33,
    order: 371,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "3/30/2022",
    quantity: 13,
    amount: "$1996.06",
    status: "cancled",
    action: null,
  },
  {
    id: 34,
    order: 296,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "11/13/2021",
    quantity: 5,
    amount: "$2749.00",
    status: "due",
    action: null,
  },
  {
    id: 35,
    order: 887,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "12/7/2021",
    quantity: 11,
    amount: "$4353.01",
    status: "paid",
    action: null,
  },
  {
    id: 36,
    order: 30,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "9/9/2021",
    quantity: 15,
    amount: "$3252.37",
    status: "due",
    action: null,
  },
  {
    id: 37,
    order: 365,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "2/12/2022",
    quantity: 5,
    amount: "$4044.10",
    status: "due",
    action: null,
  },
  {
    id: 38,
    order: 649,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "3/6/2022",
    quantity: 5,
    amount: "$3859.92",
    status: "paid",
    action: null,
  },
  {
    id: 39,
    order: 923,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "7/25/2022",
    quantity: 14,
    amount: "$1652.47",
    status: "paid",
    action: null,
  },
  {
    id: 40,
    order: 423,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "3/2/2022",
    quantity: 8,
    amount: "$2700.12",
    status: "cancled",
    action: null,
  },
  {
    id: 41,
    order: 703,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "12/8/2021",
    quantity: 8,
    amount: "$4508.13",
    status: "cancled",
    action: null,
  },
  {
    id: 42,
    order: 792,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "11/22/2021",
    quantity: 11,
    amount: "$4938.04",
    status: "due",
    action: null,
  },
  {
    id: 43,
    order: 400,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "4/6/2022",
    quantity: 1,
    amount: "$3471.32",
    status: "due",
    action: null,
  },
  {
    id: 44,
    order: 718,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "2/4/2022",
    quantity: 4,
    amount: "$4011.60",
    status: "paid",
    action: null,
  },
  {
    id: 45,
    order: 970,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "3/30/2022",
    quantity: 15,
    amount: "$3723.64",
    status: "due",
    action: null,
  },
  {
    id: 46,
    order: 786,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "11/20/2021",
    quantity: 2,
    amount: "$2441.15",
    status: "cancled",
    action: null,
  },
  {
    id: 47,
    order: 925,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "10/24/2021",
    quantity: 11,
    amount: "$1196.76",
    status: "cancled",
    action: null,
  },
  {
    id: 48,
    order: 929,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "6/30/2022",
    quantity: 10,
    amount: "$3579.57",
    status: "cancled",
    action: null,
  },
  {
    id: 49,
    order: 377,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "11/16/2021",
    quantity: 4,
    amount: "$2657.84",
    status: "due",
    action: null,
  },
  {
    id: 50,
    order: 661,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    date: "8/15/2022",
    quantity: 6,
    amount: "$2905.94",
    status: "paid",
    action: null,
  },
];

export const homeTable = [
  {
    company: user1,
    category: "Ornamental Railings",
    views: 343,
    revenue: "$231.26",
    sales: 95,
    up: false,
  },
  {
    company: user2,
    category: "Asphalt Paving",
    views: 315,
    revenue: "$432.81",
    sales: 197,
    up: false,
  },
  {
    company: user3,
    category: "Framing (Steel)",
    views: 329,
    revenue: "$437.65",
    sales: 137,
    up: true,
  },
  {
    company: user4,
    category: "Structural and Misc Steel (Fabrication)",
    views: 336,
    revenue: "$387.55",
    sales: 101,
    up: true,
  },
  {
    company: user5,
    category: "Wall Protection",
    views: 375,
    revenue: "$489.80",
    sales: 99,
    up: false,
  },
  {
    company: user6,
    category: "Marlite Panels (FED)",
    views: 490,
    revenue: "$421.45",
    sales: 101,
    up: true,
  },
  {
    company: user1,
    category: "Epoxy Flooring",
    views: 433,
    revenue: "$207.61",
    sales: 197,
    up: false,
  },
  {
    company: user2,
    category: "Epoxy Flooring",
    views: 499,
    revenue: "$392.86",
    sales: 91,
    up: false,
  },
  {
    company: user3,
    category: "Marlite Panels (FED)",
    views: 441,
    revenue: "$162.87",
    sales: 115,
    up: false,
  },
  {
    company: user4,
    category: "RF Shielding",
    views: 415,
    revenue: "$268.58",
    sales: 128,
    up: false,
  },
  {
    company: user5,
    category: "Roofing (Metal)",
    views: 303,
    revenue: "$369.19",
    sales: 179,
    up: false,
  },
  {
    company: user6,
    category: "RF Shielding",
    views: 415,
    revenue: "$420.87",
    sales: 148,
    up: false,
  },
  {
    company: user1,
    category: "Curb & Gutter",
    views: 493,
    revenue: "$420.26",
    sales: 152,
    up: false,
  },
  {
    company: user2,
    category: "Structural & Misc Steel Erection",
    views: 498,
    revenue: "$228.41",
    sales: 151,
    up: false,
  },
  {
    company: user3,
    category: "Retaining Wall and Brick Pavers",
    views: 465,
    revenue: "$140.83",
    sales: 71,
    up: false,
  },
  {
    company: user4,
    category: "Sitework & Site Utilities",
    views: 468,
    revenue: "$475.63",
    sales: 114,
    up: false,
  },
  {
    company: user5,
    category: "Framing (Steel)",
    views: 357,
    revenue: "$415.37",
    sales: 163,
    up: false,
  },
  {
    company: user6,
    category: "Waterproofing & Caulking",
    views: 487,
    revenue: "$436.53",
    sales: 170,
    up: false,
  },
  {
    company: user1,
    category: "Site Furnishings",
    views: 357,
    revenue: "$147.36",
    sales: 71,
    up: false,
  },
  {
    company: user2,
    category: "Casework",
    views: 465,
    revenue: "$121.67",
    sales: 78,
    up: false,
  },
  {
    company: user3,
    category: "Ornamental Railings",
    views: 438,
    revenue: "$213.25",
    sales: 155,
    up: false,
  },
  {
    company: user4,
    category: "Waterproofing & Caulking",
    views: 461,
    revenue: "$186.48",
    sales: 137,
    up: false,
  },
  {
    company: user5,
    category: "Masonry",
    views: 423,
    revenue: "$130.97",
    sales: 178,
    up: false,
  },
  {
    company: user6,
    category: "Curb & Gutter",
    views: 339,
    revenue: "$255.69",
    sales: 101,
    up: false,
  },
  {
    company: user1,
    category: "HVAC",
    views: 361,
    revenue: "$484.64",
    sales: 175,
    up: true,
  },
  {
    company: user2,
    category: "Exterior Signage",
    views: 353,
    revenue: "$485.51",
    sales: 176,
    up: true,
  },
  {
    company: user3,
    category: "Fire Protection",
    views: 364,
    revenue: "$449.45",
    sales: 136,
    up: true,
  },
  {
    company: user4,
    category: "Rebar & Wire Mesh Install",
    views: 493,
    revenue: "$309.61",
    sales: 163,
    up: true,
  },
  {
    company: user5,
    category: "Temp Fencing, Decorative Fencing and Gates",
    views: 393,
    revenue: "$372.45",
    sales: 180,
    up: true,
  },
  {
    company: user6,
    category: "Fire Protection",
    views: 441,
    revenue: "$470.34",
    sales: 104,
    up: false,
  },
];

export const recentOrder = [
  {
    user: {
      name: "Esther Howard",
      image: user1,
    },
    product: "Headphone",
    invoice: "#324567",
    price: "$90.99",
    status: "paid",
  },
  {
    user: {
      name: "Guy Hawkins",
      image: user2,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$78.65",
    status: "due",
  },
  {
    user: {
      name: "Bessie Cooper",
      image: user3,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$78.65",
    status: "pending",
  },
  {
    user: {
      name: "Kathryn Murphy",
      image: user4,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$38.65",
    status: "cancled",
  },
  {
    user: {
      name: "Darrell Steward",
      image: user5,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$178.65",
    status: "shipped",
  },
  {
    user: {
      name: "Darrell Steward",
      image: user6,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$74.65",
    status: "cancled",
  },
  {
    user: {
      name: "Esther Howard",
      image: user1,
    },
    product: "Headphone",
    invoice: "#324567",
    price: "$90.99",
    status: "paid",
  },
  {
    user: {
      name: "Guy Hawkins",
      image: user2,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$78.65",
    status: "due",
  },
  {
    user: {
      name: "Bessie Cooper",
      image: user3,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$78.65",
    status: "pending",
  },
  {
    user: {
      name: "Kathryn Murphy",
      image: user4,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$38.65",
    status: "cancled",
  },
  {
    user: {
      name: "Darrell Steward",
      image: user5,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$178.65",
    status: "shipped",
  },
  {
    user: {
      name: "Darrell Steward",
      image: user6,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$74.65",
    status: "cancled",
  },
  {
    user: {
      name: "Esther Howard",
      image: user1,
    },
    product: "Headphone",
    invoice: "#324567",
    price: "$90.99",
    status: "paid",
  },
  {
    user: {
      name: "Guy Hawkins",
      image: user2,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$78.65",
    status: "due",
  },
  {
    user: {
      name: "Bessie Cooper",
      image: user3,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$78.65",
    status: "pending",
  },
  {
    user: {
      name: "Kathryn Murphy",
      image: user4,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$38.65",
    status: "cancled",
  },
  {
    user: {
      name: "Darrell Steward",
      image: user5,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$178.65",
    status: "shipped",
  },
  {
    user: {
      name: "Darrell Steward",
      image: user6,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$74.65",
    status: "cancled",
  },
  {
    user: {
      name: "Esther Howard",
      image: user1,
    },
    product: "Headphone",
    invoice: "#324567",
    price: "$90.99",
    status: "paid",
  },
  {
    user: {
      name: "Guy Hawkins",
      image: user2,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$78.65",
    status: "due",
  },
  {
    user: {
      name: "Bessie Cooper",
      image: user3,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$78.65",
    status: "pending",
  },
  {
    user: {
      name: "Kathryn Murphy",
      image: user4,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$38.65",
    status: "cancled",
  },
  {
    user: {
      name: "Darrell Steward",
      image: user5,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$178.65",
    status: "shipped",
  },
  {
    user: {
      name: "Darrell Steward",
      image: user6,
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$74.65",
    status: "cancled",
  },
];

export const teamData = [
  {
    step: {
      name: "Registration",
      icon: "heroicons:document-check",
    },
    status: "complete",
  },
  {
    step: {
      name: "Payment",
      icon: "heroicons:credit-card",
    },
    status: "progress",
  },
  {
    step: {
      name: "Travel Verification",
      icon: "heroicons:globe-europe-africa",
    },
    status: "progress",
  },
  {
    step: {
      name: "Reporting",
      icon: "heroicons:user",
    },
    status: "progress",
  },
  
  {
    step: {
      name: "Accomodation",
      icon: "heroicons:home",
    },
    status: "progress",
  },
  {
    step: {
      name: "Certificate",
      icon: "heroicons:document",
    },
    status: "progress",
  },
  
];
